services:
  - type: web
    plan: free
    name: curriculum42
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.src.src.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "src.settings.production"

