services:
  - type: web
    name: curriculum42
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.src.src.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "src.settings.production"
