# Generated by Django 5.0.4 on 2024-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='3S1jKY4uBmghB2jBUto6', max_length=20),
        ),
    ]
